#!/usr/bin/env python3
# redsdice by redjard 2025-11-14 GPL3

import sys  # to get the command arguments
from secrets import randbelow  # for secure randomness
import re  # to parse the dnd dice descriptor into its parts

if len(sys.argv) < 2:
    print(f'Usage: {sys.argv[0]} <DnD dice descriptor> [...]\n\nExamples:\n{sys.argv[0]} d20\n{sys.argv[0]} 4d18 d12 1d8 1d34-8')

def roll(dicedesc):
    dicedesc = re.match(r"(?P<amount>\d*)d(?P<size>\d*)(?P<modifier>[+-]\d+)?",dicedesc)
    
    amount   = dicedesc.group("amount") or 1
    size     = dicedesc.group("size")
    modifier = dicedesc.group("modifier") or 0
    
    amount   = int(amount)
    size     = int(size)
    modifier = int(modifier)
    
    for _ in range(amount):
        roll = randbelow(size) + 1
        roll += modifier
        print(f'd{size}: \t{roll}')
    

for die in sys.argv[1:]:
    roll(die)
